<!-- FlexSlider pieces -->
	<link rel="stylesheet" href="../css/default-five-slides.css" type="text/css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="../js/jquery.flexslider-min.js"></script>
	<script src="../js/css3-mediaqueries.js"></script>
	
	<!-- Kwiks pieces -->
	<script src="../js/kwiks.js"></script>
	
	<!-- Includes for this demo -->
	<link rel="stylesheet" href="../css/demo.css" type="text/css" media="screen" />
