	<a href="http://localhost:8080/FinalProject/Project/Home.jsp" data-icon="home" class="ui-btn-left" data-ajax="false" style="color:#FFFFFF;" >Home</a>
		<h1>Korea Baseball</h1>

	<a class="menuBtn" data-ajax="false" data-icon="arrow-d" data-ajax="false" style="color:#FFFFFF;">Menu</a>
		<nav id="navigation-list">
			<ul>                    <!--data-ajax="false"가 있어야 연결이 제대로 됨-->
							<!--#FFFFFF 흰색 글씨-->
				<li><a href="http://localhost:8080/FinalProject/Project/Introduce.jsp" style="color:#FFFFFF;" data-ajax="false">Introduce</a></li>
				<li><a href="http://localhost:8080/FinalProject/Project/Operation.jsp" style="color:#FFFFFF;" data-ajax="false">Operation</a></li>
				<li><a href="http://localhost:8080/FinalProject/Project/Schedule.jsp" style="color:#FFFFFF;" data-ajax="false">Schedule</a></li>
				<li><a href="http://localhost:8080/FinalProject/Project/Club.jsp" style="color:#FFFFFF;" data-ajax="false">Club</a></li>
				<li><a href="http://localhost:8080/FinalProject/Project/ClubRank.jsp" style="color:#FFFFFF;" data-ajax="false">Ranking</a></li>
				<li><a href="http://m.ticket.interpark.com/rank/index.html?gr=SP&st=RR" style="color:#FFFFFF;" data-ajax="false">Reservation</a></li>
				
			</ul>
		</nav>